source 'https://rubygems.org'

gem 'rails', '5.2.1'
gem 'sass-rails'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'rails_12factor'
gem 'nokogiri'
gem 'albino'
gem 'github-markdown'
gem 'pg', '~> 0.20.0'
gem 'coderay'
gem 'bcrypt'
gem 'toastr-rails'
gem 'puma'
gem 'friendly_id'
gem 'font-awesome-sass', '~> 4.6.2'
gem 'mengpaneel'
gem 'client_side_validations'
gem 'validate_url'
gem 'gon'
gem 'web-console', group: :development
group :development, :test do
  gem 'byebug'
  gem 'pry'
  gem 'spring'
end